# Analysis of Minor League Challenge Systems

In this file we will analyze the data we prepared in `data_prep.ipynb`.

## Questions to Pursue

1) What types of pitches and pitch locations are challenged most frequently?

2) How often are challenges successful?

3) Which batters / teams challenge most frequently?

4) Who uses their challenges most / least effectively? Could incorporate run values here

5) Can we create a challenge 'player card' visualization as a proof of concept?

## Current Blockers

1) It turns out that sz_top and sz_bottom don't align perfectly with the top and bottom of the strike zone. It would be helpful to definitiely determine whether a challenge will be successful to analyze 'missed opportunities'.

## Next Steps

1) Begin analysis with the questions above as a guide.

2) Look into using the zone column to determine whether a pitch is in the strike zone.

# Import Libraries

In [1]:
import numpy as np
import polars as pl

# Load Data

In [2]:
pbp = pl.read_csv('../data/export_data/aaa_pbp.csv')

In [3]:
pbp.head()

shape: (5, 111)
┌──────────┬────────────┬────────────┬────────────┬───┬────────────┬───────┬───────────┬───────────┐
│ pitch_id ┆ play_start ┆ play_end_d ┆ pitch_type ┆ … ┆ lag_strike ┆ swing ┆ challenge ┆ challenge │
│ ---      ┆ _datetime  ┆ atetime    ┆ ---        ┆   ┆ s          ┆ ---   ┆ ---       ┆ _successf │
│ i64      ┆ ---        ┆ ---        ┆ str        ┆   ┆ ---        ┆ str   ┆ i64       ┆ ul        │
│          ┆ str        ┆ str        ┆            ┆   ┆ i64        ┆       ┆           ┆ ---       │
│          ┆            ┆            ┆            ┆   ┆            ┆       ┆           ┆ str       │
╞══════════╪════════════╪════════════╪════════════╪═══╪════════════╪═══════╪═══════════╪═══════════╡
│ 0        ┆ 2024-06-28 ┆ 2024-06-28 ┆ CH         ┆ … ┆ 0          ┆ take  ┆ 0         ┆ no        │
│          ┆ T01:53:58. ┆ 01:54:02.7 ┆            ┆   ┆            ┆       ┆           ┆ challenge │
│          ┆ 280        ┆ 89         ┆            ┆   ┆            ┆       ┆           ┆           │
│ 1        ┆ 2024-09-18 ┆ 2024-09-18 ┆ FF         ┆ … ┆ 0          ┆ take  ┆ 0         ┆ no        │
│          ┆ T00:19:15. ┆ 00:19:25.6 ┆            ┆   ┆            ┆       ┆           ┆ challenge │
│          ┆ 010        ┆ 47         ┆            ┆   ┆            ┆       ┆           ┆           │
│ 2        ┆ 2024-07-25 ┆ 2024-07-25 ┆ SL         ┆ … ┆ 2          ┆ take  ┆ 0         ┆ no        │
│          ┆ T03:06:15. ┆ 03:06:19.2 ┆            ┆   ┆            ┆       ┆           ┆ challenge │
│          ┆ 107        ┆ 95         ┆            ┆   ┆            ┆       ┆           ┆           │
│ 3        ┆ 2024-08-03 ┆ 2024-08-03 ┆ FF         ┆ … ┆ 2          ┆ take  ┆ 0         ┆ no        │
│          ┆ T22:40:47. ┆ 22:40:51.5 ┆            ┆   ┆            ┆       ┆           ┆ challenge │
│          ┆ 492        ┆ 01         ┆            ┆   ┆            ┆       ┆           ┆           │
│ 4        ┆ 2024-08-16 ┆ 2024-08-16 ┆ CU         ┆ … ┆ 2          ┆ take  ┆ 0         ┆ no        │
│          ┆ T23:05:44. ┆ 23:05:51.5 ┆            ┆   ┆            ┆       ┆           ┆ challenge │
│          ┆ 932        ┆ 95         ┆            ┆   ┆            ┆       ┆           ┆           │
└──────────┴────────────┴────────────┴────────────┴───┴────────────┴───────┴───────────┴───────────┘

In [4]:
# add a column to identify the team that challenged (empty if no challenge)
pbp = pbp.with_columns([
    pl.when(
        (pl.col('challenge') == 1) &
        (pl.col('des').str.contains('challenged'))
        )
    .then(
        pl.col('des')
        .str.split('challenged')
        .list.first()
        .str.strip_chars()
    )
    .otherwise(pl.lit(""))
    .alias('challenge_team'),

    pl.when(
        (
            (pl.col('challenge_successful') == 'unsuccessful') &
            (pl.col('balls') > pl.col('lag_balls'))
        ) |
        (
            (pl.col('challenge_successful') == 'successful') &
            (pl.col('balls') == pl.col('lag_balls'))
        )
    )
    .then(pl.lit('ball'))
    .when(
        (
            (pl.col('challenge_successful') == 'unsuccessful') &
            (pl.col('strikes') > pl.col('lag_strikes'))
        ) |
        (
            (pl.col('challenge_successful') == 'successful') &
            (pl.col('strikes') == pl.col('lag_strikes'))
        )
    )
    .then(pl.lit('strike'))
    .otherwise(pl.lit(''))
    .alias('original_call_challenge'),
    
    pl.when(
        (
            (pl.col('challenge_successful') == 'successful') &
            (pl.col('strikes') > pl.col('lag_strikes'))
        ) |
        (
            (pl.col('challenge_successful') == 'unsuccessful') &
            (pl.col('strikes') == pl.col('lag_strikes'))
        )
    )
    .then(pl.lit('Pitching'))
    .when(
        (
            (pl.col('challenge_successful') == 'successful') &
            (pl.col('balls') > pl.col('lag_balls'))
        ) |
        (
            (pl.col('challenge_successful') == 'unsuccessful') &
            (pl.col('balls') == pl.col('lag_balls'))
        )
    )
    .then(pl.lit('Batting'))
    .otherwise(pl.lit(''))
    .alias('challenge_side')
]
)

# Classify Pitch as In or Outside of Strikezone

**Horizontal limits:** x is centered at 0 and measured in feet. Home plate is 17 inches wide, and the strike zone's horizontal limits include home plate plus the diameter of the baseball (2.94 inches) = 19.94 inches = 1.66 feet. Thus, the limits of the strike zone are +- 0.83.

**Vertical limits:** Right now we're using sz_top and sz_bot +/- the diameter of the ball, but as we'll see below it's not entirely consistent with ABS results.

In [5]:
ball_types = ['B', '*B', 'P']
pbp = (
    pbp
        .with_columns(
            pl.when(
                (np.abs(pl.col('plate_x')) < 0.83) &
                (pl.col('plate_z') >= (pl.col('sz_bot') - (2.94 / 12))) &
                (pl.col('plate_z') <= (pl.col('sz_top') + (2.94 / 12)))
            )
            .then(1)
            .otherwise(0)
            .alias('in_strike_zone')
            )
        .with_columns(
            # called a ball, but in the strike zone
            pl.when(
                (
                    (pl.col('type').is_in(ball_types)) &
                    (pl.col('in_strike_zone') == 1)
                ) |
                # called a strike, but not in the strike zone
                (
                    (pl.col('swing') == 'take') &
                    (pl.col('strikes') > pl.col('lag_strikes')) &
                    (pl.col('in_strike_zone') == 0)
                )
            )
            .then(1)
            .otherwise(0)
            .alias('missed_call')
        )
)

# Visualize Normalized Location of Pitches

- Convert height of pitch into percentile of bottom to top of strike zone for consistent plotting

formula: 100 * (pitch height - bottom of zone) / (top of zone - bottom of zone)

In [6]:
delta = 2.94 / 12
pbp = pbp.with_columns(
    (
        100 * (
            pl.col('plate_z') - (pl.col('sz_bot') - delta)
        ) / (
            (pl.col('sz_top') + delta) - (pl.col('sz_bot') - delta)
        )
    )
    # set upper and lower bounds to prevent skewing of graph
    .clip(-100, 200)
    .alias('percentile_z')
)

## Challenges -- Result Strike

In [7]:
(
    pbp
        .filter(
            (pl.col('challenge') == 1) &
            (pl.col('strikes') > pl.col('lag_strikes'))
        )
        .group_by(pl.col('strikes'))
        .len()
)

shape: (3, 2)
┌─────────┬─────┐
│ strikes ┆ len │
│ ---     ┆ --- │
│ i64     ┆ u32 │
╞═════════╪═════╡
│ 3       ┆ 623 │
│ 1       ┆ 1   │
│ 2       ┆ 1   │
└─────────┴─────┘

In [8]:
challenge_s = (
    pbp
        .filter(
            (pl.col('challenge') == 1) &
            (pl.col('strikes') == 3)
        )
)
challenge_s = challenge_s.with_columns(
    pl.when(pl.col('challenge_successful') == 'successful')
    .then(pl.lit('green'))
    .otherwise(pl.lit('red'))
    .alias('challenge_color')
)

In [9]:
import plotly.graph_objects as go

tooltip = challenge_s.select([
    'challenge_team',
    'challenge_side',
    'plate_x',
    'percentile_z',
    'original_call_challenge',
    'challenge_successful'
]).to_numpy()
fig = go.Figure()
# strike zone
fig.add_shape(
    type="rect",
    x0=-0.83, x1=0.83,
    y0=0, y1=100,
    fillcolor="rgba(173, 216, 230, 0.3)",
    line=dict(color="black", width=2)
)
# scatter plot of pitches
fig.add_trace(go.Scatter(
    x=challenge_s["plate_x"],
    y=challenge_s["percentile_z"],
    mode='markers',
    marker=dict(
        color=challenge_s['challenge_color'],
        colorscale = 'RdBu',
        line = dict(width = 0),
        size= 15
        ),
    name='Pitches',
    showlegend = False,
    customdata = tooltip,
    hovertemplate = (
        "Challenge Team: %{customdata[0]}<br>" +
        "Challenge Side: %{customdata[1]}<br>" +
        "Horizontal Location: %{customdata[2]:.2f}<br>" +
        "Vertical Location (%ile): %{customdata[3]:.1f}<br>" +
        "Initial Call: %{customdata[4]}<br>" +
        "Challenge: %{customdata[5]}<extra></extra>"
    )
))
# legend for successful challenges
fig.add_trace(go.Scatter(
    x=[None], y=[None],
    mode='markers',
    marker=dict(size=15, color='green'),
    name='Successful'
))
# legend for unsuccessful challenges
fig.add_trace(go.Scatter(
    x=[None], y=[None],
    mode='markers',
    marker=dict(size=15, color='red'),
    name='Unsuccessful'
))
# formatting
fig.update_layout(
    width=500,
    height=700,
    xaxis=dict(
        showgrid=False,
        zeroline=False,
        visible=False,
        range=[-1.1, 1.1]
    ),
    yaxis=dict(
        showgrid=False,
        zeroline=False,
        visible=False,
        range=[-20, 120]
    ),
    plot_bgcolor='white',
    margin=dict(l=0, r=0, t=30, b=0),
    title = dict(
        text = "Locations of Challenges -- Result = Strike",
        font = dict(family = "Arial", size = 24, color = "black"),
        x = 0.5,
        y = 0.96,
        xanchor = 'center'
    ),
    legend = dict(
        y = 0.95,
        x = 0.64
    )
)

fig.show()

## Challenges Resulting in a Ball

In [10]:
challenge_b = (
    pbp
        .filter(
            (pl.col('challenge') == 1) &
            (pl.col('balls') == 4)
        )
        .with_columns(
            pl.when(pl.col('challenge_successful') == 'successful')
            .then(pl.lit('green'))
            .otherwise(pl.lit('red'))
            .alias('challenge_color')
        )
)

In [11]:
import plotly.graph_objects as go

tooltip = challenge_b.select([
    'challenge_team',
    'challenge_side',
    'plate_x',
    'percentile_z',
    'original_call_challenge',
    'challenge_successful'
]).to_numpy()
fig = go.Figure()
# strike zone
fig.add_shape(
    type="rect",
    x0=-0.83, x1=0.83,
    y0=0, y1=100,
    fillcolor="rgba(173, 216, 230, 0.3)",
    line=dict(color="black", width=2)
)
# scatter plot of pitches
fig.add_trace(go.Scatter(
    x=challenge_b["plate_x"],
    y=challenge_b["percentile_z"],
    mode='markers',
    marker=dict(
        color=challenge_b['challenge_color'],
        colorscale = 'RdBu',
        line = dict(width = 0),
        size= 15
        ),
    name='Pitches',
    showlegend = False,
    customdata = tooltip,
    hovertemplate = (
        "Challenge Team: %{customdata[0]}<br>" +
        "Challenge Side: %{customdata[1]}<br>" +
        "Horizontal Location: %{customdata[2]:.2f}<br>" +
        "Vertical Location (%ile): %{customdata[3]:.1f}<br>" +
        "Initial Call: %{customdata[4]}<br>" +
        "Challenge: %{customdata[5]}<extra></extra>"
    )
))
# legend for successful challenges
fig.add_trace(go.Scatter(
    x=[None], y=[None],
    mode='markers',
    marker=dict(size=15, color='green'),
    name='Successful'
))
# legend for unsuccessful challenges
fig.add_trace(go.Scatter(
    x=[None], y=[None],
    mode='markers',
    marker=dict(size=15, color='red'),
    name='Unsuccessful'
))
# formatting
fig.update_layout(
    width=500,
    height=700,
    xaxis=dict(
        showgrid=False,
        zeroline=False,
        visible=False,
        range=[-1.2, 1.2]
    ),
    yaxis=dict(
        showgrid=False,
        zeroline=False,
        visible=False,
        range=[-40, 140]
    ),
    plot_bgcolor='white',
    margin=dict(l=0, r=0, t=30, b=0),
    title = dict(
        text = "Locations of Challenges -- Result = Ball",
        font = dict(family = "Arial", size = 24, color = "black"),
        x = 0.5,
        y = 0.96,
        xanchor = 'center'
    ),
    legend = dict(
        y = 0.95,
        x = 0.64
    )
)

fig.show()

# Table of Challenge Success Rates

1) team

2) pitching: num challenges and success rate

3) batting: num challenges and success rate

In [12]:
def success_rate(side: str) -> pl.Expr:
    return (
        pl.when(pl.col("challenge_side") == side)
        .then(pl.col("challenge_successful_binary"))
        .otherwise(None)
        .mean()
        .alias(f"{side.lower()}_success_rate")
    )
team_metrics = (
    pbp
        .with_columns(
            pl.when(pl.col('challenge_successful') == 'successful')
            .then(1)
            .otherwise(0)
            .alias('challenge_successful_binary')
        )
        .filter(pl.col('challenge') == 1)
        .group_by('challenge_team')
        .agg(
            (pl.col('challenge_side') == 'Pitching').sum().alias("num_pitching_challenges"),
            (pl.col('challenge_side') == 'Batting').sum().alias("num_batting_challenges"),
            success_rate('Batting'),
            success_rate('Pitching')
        )
)

In [13]:
from great_tables import GT
import polars.selectors as cs
(
    GT(
        team_metrics
            .sort('num_batting_challenges', descending = True)
    )
    .cols_move(
        columns = [ 'num_batting_challenges', 'batting_success_rate', 'num_pitching_challenges', 'pitching_success_rate'],
        after = 'challenge_team'
    )
    .tab_header("Team Challenge Metrics")
    .tab_spanner(
        "Pitching",
        columns = ['num_pitching_challenges', 'pitching_success_rate']
    )
    .tab_spanner(
        "Batting",
        columns = ['num_batting_challenges', 'batting_success_rate']
    )
    .cols_label(
        challenge_team = "Team",
        num_pitching_challenges = "#",
        pitching_success_rate = "Win Rate",
        num_batting_challenges = "#",
        batting_success_rate = "Win Rate"
    )
    .fmt_percent(['pitching_success_rate', 'batting_success_rate'], decimals = 1)
    .opt_stylize(1)
)

GT(_tbl_data=shape: (30, 5)
┌────────────────┬────────────────────┬────────────────────┬───────────────────┬───────────────────┐
│ challenge_team ┆ num_pitching_chall ┆ num_batting_challe ┆ batting_success_r ┆ pitching_success_ │
│ ---            ┆ enges              ┆ nges               ┆ ate               ┆ rate              │
│ str            ┆ ---                ┆ ---                ┆ ---               ┆ ---               │
│                ┆ u32                ┆ u32                ┆ f64               ┆ f64               │
╞════════════════╪════════════════════╪════════════════════╪═══════════════════╪═══════════════════╡
│ Space Cowboys  ┆ 7                  ┆ 35                 ┆ 0.171429          ┆ 0.571429          │
│ Isotopes       ┆ 11                 ┆ 31                 ┆ 0.193548          ┆ 0.272727          │
│ River Cats     ┆ 8                  ┆ 29                 ┆ 0.172414          ┆ 0.25              │
│ Bats           ┆ 3                  ┆ 29                 ┆ 0.413793          ┆ 0.333333          │
│ Aviators       ┆ 14                 ┆ 28                 ┆ 0.25              ┆ 0.285714          │
│ …              ┆ …                  ┆ …                  ┆ …                 ┆ …                 │
│ Jumbo Shrimp   ┆ 9                  ┆ 17                 ┆ 0.117647          ┆ 0.444444          │
│ Bulls          ┆ 5                  ┆ 16                 ┆ 0.125             ┆ 0.0               │
│ IronPigs       ┆ 4                  ┆ 16                 ┆ 0.0625            ┆ 0.25              │
│ Indians        ┆ 8                  ┆ 13                 ┆ 0.0               ┆ 0.125             │
│ Stripers       ┆ 6                  ┆ 5                  ┆ 0.2               ┆ 0.166667          │
└────────────────┴────────────────────┴────────────────────┴───────────────────┴───────────────────┘, _body=<great_tables._gt_data.Body object at 0x000001D58E538C20>, _boxhead=Boxhead([ColInfo(var='challenge_team', type=<ColInfoTypeEnum.default: 1>, column_label='Team', column_align='left', column_width=None), ColInfo(var='num_batting_challenges', type=<ColInfoTypeEnum.default: 1>, column_label='#', column_align='right', column_width=None), ColInfo(var='batting_success_rate', type=<ColInfoTypeEnum.default: 1>, column_label='Win Rate', column_align='right', column_width=None), ColInfo(var='num_pitching_challenges', type=<ColInfoTypeEnum.default: 1>, column_label='#', column_align='right', column_width=None), ColInfo(var='pitching_success_rate', type=<ColInfoTypeEnum.default: 1>, column_label='Win Rate', column_align='right', column_width=None)]), _stub=<great_tables._gt_data.Stub object at 0x000001D58E538980>, _spanners=Spanners([SpannerInfo(spanner_id='Pitching', spanner_level=0, spanner_label='Pitching', spanner_units=None, spanner_pattern=None, vars=['num_pitching_challenges', 'pitching_success_rate'], built=None), SpannerInfo(spanner_id='Batting', spanner_level=0, spanner_label='Batting', spanner_units=None, spanner_pattern=None, vars=['num_batting_challenges', 'batting_success_rate'], built=None)]), _heading=Heading(title='Team Challenge Metrics', subtitle=None, preheader=None), _stubhead=None, _source_notes=[], _footnotes=[], _styles=[], _locale=<great_tables._gt_data.Locale object at 0x000001D58E539010>, _formats=[<great_tables._gt_data.FormatInfo object at 0x000001D58E538D70>], _substitutions=[], _options=Options(table_id=OptionsInfo(scss=False, category='table', type='value', value=None), table_caption=OptionsInfo(scss=False, category='table', type='value', value=None), table_width=OptionsInfo(scss=True, category='table', type='px', value='auto'), table_layout=OptionsInfo(scss=True, category='table', type='value', value='fixed'), table_margin_left=OptionsInfo(scss=True, category='table', type='px', value='auto'), table_margin_right=OptionsInfo(scss=True, category='table', type='px', value='auto'), table_background_color=OptionsInfo(scss=True, category='table', type='value', value='#FFFFFF'), table_additional_css=OptionsInfo(scss=False, category='table', type='values', value=[]), table_font_names=OptionsInfo(scss=False, category='table', type='values', value=['-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Roboto', 'Oxygen', 'Ubuntu', 'Cantarell', 'Helvetica Neue', 'Fira Sans', 'Droid Sans', 'Arial', 'sans-serif']), table_font_size=OptionsInfo(scss=True, category='table', type='px', value='16px'), table_font_weight=OptionsInfo(scss=True, category='table', type='value', value='normal'), table_font_style=OptionsInfo(scss=True, category='table', type='value', value='normal'), table_font_color=OptionsInfo(scss=True, category='table', type='value', value='#333333'), table_font_color_light=OptionsInfo(scss=True, category='table', type='value', value='#FFFFFF'), table_border_top_include=OptionsInfo(scss=False, category='table', type='boolean', value=True), table_border_top_style=OptionsInfo(scss=True, category='table', type='value', value='solid'), table_border_top_width=OptionsInfo(scss=True, category='table', type='px', value='2px'), table_border_top_color=OptionsInfo(scss=True, category='table', type='value', value='#004D80'), table_border_right_style=OptionsInfo(scss=True, category='table', type='value', value='none'), table_border_right_width=OptionsInfo(scss=True, category='table', type='px', value='2px'), table_border_right_color=OptionsInfo(scss=True, category='table', type='value', value='#D3D3D3'), table_border_bottom_include=OptionsInfo(scss=False, category='table', type='boolean', value=True), table_border_bottom_style=OptionsInfo(scss=True, category='table', type='value', value='solid'), table_border_bottom_width=OptionsInfo(scss=True, category='table', type='px', value='2px'), table_border_bottom_color=OptionsInfo(scss=True, category='table', type='value', value='#004D80'), table_border_left_style=OptionsInfo(scss=True, category='table', type='value', value='none'), table_border_left_width=OptionsInfo(scss=True, category='table', type='px', value='2px'), table_border_left_color=OptionsInfo(scss=True, category='table', type='value', value='#D3D3D3'), heading_background_color=OptionsInfo(scss=True, category='heading', type='value', value=None), heading_align=OptionsInfo(scss=True, category='heading', type='value', value='center'), heading_title_font_size=OptionsInfo(scss=True, category='heading', type='px', value='125%'), heading_title_font_weight=OptionsInfo(scss=True, category='heading', type='value', value='initial'), heading_subtitle_font_size=OptionsInfo(scss=True, category='heading', type='px', value='85%'), heading_subtitle_font_weight=OptionsInfo(scss=True, category='heading', type='value', value='initial'), heading_padding=OptionsInfo(scss=True, category='heading', type='px', value='4px'), heading_padding_horizontal=OptionsInfo(scss=True, category='heading', type='px', value='5px'), heading_border_bottom_style=OptionsInfo(scss=True, category='heading', type='value', value='solid'), heading_border_bottom_width=OptionsInfo(scss=True, category='heading', type='px', value='2px'), heading_border_bottom_color=OptionsInfo(scss=True, category='heading', type='value', value='#0076BA'), heading_border_lr_style=OptionsInfo(scss=True, category='heading', type='value', value='none'), heading_border_lr_width=OptionsInfo(scss=True, category='heading', type='px', value='1px'), heading_border_lr_color=OptionsInfo(scss=True, category='heading', type='value', value='#D3D3D3'), column_labels_background_color=OptionsInfo(scss=True, category='column_labels', type='value', value='#FFFFFF'), column_labels_font_size=OptionsInfo(scss=True, category='column_labels', type='px', value='100%'), column_labels_font_weight=OptionsInfo(scss=True, category='column_labels', type='value', value='normal'), column_labels_text_transform=OptionsInfo(scss=True, category='column_labels', type='value', value='inherit'), column_labels_padding=OptionsInfo(scss=True, category='column_labels', type='px', value='5px'), column_labels_padding_horizontal=OptionsInfo(scss=True, category='column_labels', type='px', value='5px'), column_labels_vlines_style=OptionsInfo(scss=True, category='table_body', type='value', value='none'), column_labels_vlines_width=OptionsInfo(scss=True, category='table_body', type='px', value='1px'), column_labels_vlines_color=OptionsInfo(scss=True, category='table_body', type='value', value='#D3D3D3'), column_labels_border_top_style=OptionsInfo(scss=True, category='column_labels', type='value', value='solid'), column_labels_border_top_width=OptionsInfo(scss=True, category='column_labels', type='px', value='2px'), column_labels_border_top_color=OptionsInfo(scss=True, category='column_labels', type='value', value='#0076BA'), column_labels_border_bottom_style=OptionsInfo(scss=True, category='column_labels', type='value', value='solid'), column_labels_border_bottom_width=OptionsInfo(scss=True, category='column_labels', type='px', value='2px'), column_labels_border_bottom_color=OptionsInfo(scss=True, category='column_labels', type='value', value='#0076BA'), column_labels_border_lr_style=OptionsInfo(scss=True, category='column_labels', type='value', value='none'), column_labels_border_lr_width=OptionsInfo(scss=True, category='column_labels', type='px', value='1px'), column_labels_border_lr_color=OptionsInfo(scss=True, category='column_labels', type='value', value='#D3D3D3'), column_labels_hidden=OptionsInfo(scss=False, category='column_labels', type='boolean', value=False), row_group_background_color=OptionsInfo(scss=True, category='row_group', type='value', value=None), row_group_font_size=OptionsInfo(scss=True, category='row_group', type='px', value='100%'), row_group_font_weight=OptionsInfo(scss=True, category='row_group', type='value', value='initial'), row_group_text_transform=OptionsInfo(scss=True, category='row_group', type='value', value='inherit'), row_group_padding=OptionsInfo(scss=True, category='row_group', type='px', value='8px'), row_group_padding_horizontal=OptionsInfo(scss=True, category='row_group', type='px', value='5px'), row_group_border_top_style=OptionsInfo(scss=True, category='row_group', type='value', value='solid'), row_group_border_top_width=OptionsInfo(scss=True, category='row_group', type='px', value='2px'), row_group_border_top_color=OptionsInfo(scss=True, category='row_group', type='value', value='#0076BA'), row_group_border_right_style=OptionsInfo(scss=True, category='row_group', type='value', value='none'), row_group_border_right_width=OptionsInfo(scss=True, category='row_group', type='px', value='1px'), row_group_border_right_color=OptionsInfo(scss=True, category='row_group', type='value', value='#D3D3D3'), row_group_border_bottom_style=OptionsInfo(scss=True, category='row_group', type='value', value='solid'), row_group_border_bottom_width=OptionsInfo(scss=True, category='row_group', type='px', value='2px'), row_group_border_bottom_color=OptionsInfo(scss=True, category='row_group', type='value', value='#0076BA'), row_group_border_left_style=OptionsInfo(scss=True, category='row_group', type='value', value='none'), row_group_border_left_width=OptionsInfo(scss=True, category='row_group', type='px', value='1px'), row_group_border_left_color=OptionsInfo(scss=True, category='row_group', type='value', value='#D3D3D3'), row_group_as_column=OptionsInfo(scss=False, category='row_group', type='boolean', value=False), table_body_hlines_style=OptionsInfo(scss=True, category='table_body', type='value', value='none'), table_body_hlines_width=OptionsInfo(scss=True, category='table_body', type='px', value='1px'), table_body_hlines_color=OptionsInfo(scss=True, category='table_body', type='value', value='#89D3FE'), table_body_vlines_style=OptionsInfo(scss=True, category='table_body', type='value', value='none'), table_body_vlines_width=OptionsInfo(scss=True, category='table_body', type='px', value='1px'), table_body_vlines_color=OptionsInfo(scss=True, category='table_body', type='value', value='#89D3FE'), table_body_border_top_style=OptionsInfo(scss=True, category='table_body', type='value', value='solid'), table_body_border_top_width=OptionsInfo(scss=True, category='table_body', type='px', value='2px'), table_body_border_top_color=OptionsInfo(scss=True, category='table_body', type='value', value='#0076BA'), table_body_border_bottom_style=OptionsInfo(scss=True, category='table_body', type='value', value='solid'), table_body_border_bottom_width=OptionsInfo(scss=True, category='table_body', type='px', value='2px'), table_body_border_bottom_color=OptionsInfo(scss=True, category='table_body', type='value', value='#0076BA'), data_row_padding=OptionsInfo(scss=True, category='data_row', type='px', value='8px'), data_row_padding_horizontal=OptionsInfo(scss=True, category='data_row', type='px', value='5px'), stub_background_color=OptionsInfo(scss=True, category='stub', type='value', value='#0076BA'), stub_font_size=OptionsInfo(scss=True, category='stub', type='px', value='100%'), stub_font_weight=OptionsInfo(scss=True, category='stub', type='value', value='initial'), stub_text_transform=OptionsInfo(scss=True, category='stub', type='value', value='inherit'), stub_border_style=OptionsInfo(scss=True, category='stub', type='value', value='solid'), stub_border_width=OptionsInfo(scss=True, category='stub', type='px', value='2px'), stub_border_color=OptionsInfo(scss=True, category='stub', type='value', value='#0076BA'), stub_row_group_background_color=OptionsInfo(scss=True, category='stub', type='value', value=None), stub_row_group_font_size=OptionsInfo(scss=True, category='stub', type='px', value='100%'), stub_row_group_font_weight=OptionsInfo(scss=True, category='stub', type='value', value='initial'), stub_row_group_text_transform=OptionsInfo(scss=True, category='stub', type='value', value='inherit'), stub_row_group_border_style=OptionsInfo(scss=True, category='stub', type='value', value='solid'), stub_row_group_border_width=OptionsInfo(scss=True, category='stub', type='px', value='2px'), stub_row_group_border_color=OptionsInfo(scss=True, category='stub', type='value', value='#D3D3D3'), source_notes_padding=OptionsInfo(scss=True, category='source_notes', type='px', value='4px'), source_notes_padding_horizontal=OptionsInfo(scss=True, category='source_notes', type='px', value='5px'), source_notes_background_color=OptionsInfo(scss=True, category='source_notes', type='value', value=None), source_notes_font_size=OptionsInfo(scss=True, category='source_notes', type='px', value='90%'), source_notes_border_bottom_style=OptionsInfo(scss=True, category='source_notes', type='value', value='none'), source_notes_border_bottom_width=OptionsInfo(scss=True, category='source_notes', type='px', value='2px'), source_notes_border_bottom_color=OptionsInfo(scss=True, category='source_notes', type='value', value='#D3D3D3'), source_notes_border_lr_style=OptionsInfo(scss=True, category='source_notes', type='value', value='none'), source_notes_border_lr_width=OptionsInfo(scss=True, category='source_notes', type='px', value='2px'), source_notes_border_lr_color=OptionsInfo(scss=True, category='source_notes', type='value', value='#D3D3D3'), source_notes_multiline=OptionsInfo(scss=False, category='source_notes', type='boolean', value=True), source_notes_sep=OptionsInfo(scss=False, category='source_notes', type='value', value=' '), row_striping_background_color=OptionsInfo(scss=True, category='row', type='value', value='#F4F4F4'), row_striping_include_stub=OptionsInfo(scss=False, category='row', type='boolean', value=False), row_striping_include_table_body=OptionsInfo(scss=False, category='row', type='boolean', value=['True']), container_width=OptionsInfo(scss=False, category='container', type='px', value='auto'), container_height=OptionsInfo(scss=False, category='container', type='px', value='auto'), container_padding_x=OptionsInfo(scss=False, category='container', type='px', value='0px'), container_padding_y=OptionsInfo(scss=False, category='container', type='px', value='10px'), container_overflow_x=OptionsInfo(scss=False, category='container', type='overflow', value='auto'), container_overflow_y=OptionsInfo(scss=False, category='container', type='overflow', value='auto'), quarto_disable_processing=OptionsInfo(scss=False, category='quarto', type='logical', value=False), quarto_use_bootstrap=OptionsInfo(scss=False, category='quarto', type='logical', value=False)), _has_built=False)

Other columns to add to this table:

- RV gained / lost
- Missed challenge opportunities

# Challenges by Team

Goal: write function to show the challenges by team and side (pitching / batting)

Next: missed challenge opportunities

In [14]:
def plot_challenge_results(df, challenge_team, challenge_side):
    """ 
    Plots challenge results for the inputted team and side (batting or pitching).

    Parameters
    ----------
    df: polars.DataFrame
        play-by-play dataframe containing challenge information and pitch locations.
    challenge_team: str
        The name of the challenging team (e.g., "IronPigs")
    challenge_side: str
        Indicates whether the challenging team was "Batting" or "Pitching".

    Returns
    -------
    None
        Displays an interactive Plotly figure with pitch locations and challenge results.
    """
    challenge_df = (
        df
            .filter(
                (pl.col('challenge_team') == challenge_team) &
                (pl.col('challenge_side') == challenge_side))
            .with_columns(
                pl.when(pl.col('challenge_successful') == 'successful')
                .then(pl.lit('green'))
                .otherwise(pl.lit('red'))
                .alias('challenge_color'))
    )
    import plotly.graph_objects as go

    tooltip = challenge_df.select([
        'challenge_team',
        'challenge_side',
        'plate_x',
        'percentile_z',
        'original_call_challenge',
        'challenge_successful'
    ]).to_numpy()
    fig = go.Figure()
    # strike zone
    fig.add_shape(
        type="rect",
        x0=-0.83, x1=0.83,
        y0=0, y1=100,
        fillcolor="rgba(173, 216, 230, 0.3)",
        line=dict(color="black", width=2)
    )
    # scatter plot of pitches
    fig.add_trace(go.Scatter(
        x=challenge_df["plate_x"],
        y=challenge_df["percentile_z"],
        mode='markers',
        marker=dict(
            color=challenge_df['challenge_color'],
            colorscale = 'RdBu',
            line = dict(width = 0),
            size= 15
            ),
        name='Pitches',
        showlegend = False,
        customdata = tooltip,
        hovertemplate = (
            "Challenge Team: %{customdata[0]}<br>" +
            "Challenge Side: %{customdata[1]}<br>" +
            "Horizontal Location: %{customdata[2]:.2f}<br>" +
            "Vertical Location (%ile): %{customdata[3]:.1f}<br>" +
            "Initial Call: %{customdata[4]}<br>" +
            "Challenge: %{customdata[5]}<extra></extra>"
        )
    ))
    # legend for successful challenges
    fig.add_trace(go.Scatter(
        x=[None], y=[None],
        mode='markers',
        marker=dict(size=15, color='green'),
        name='Successful'
    ))
    # legend for unsuccessful challenges
    fig.add_trace(go.Scatter(
        x=[None], y=[None],
        mode='markers',
        marker=dict(size=15, color='red'),
        name='Unsuccessful'
    ))
    # formatting
    fig.update_layout(
        width=500,
        height=700,
        xaxis=dict(
            showgrid=False,
            zeroline=False,
            visible=False,
            range=[-1.1, 1.1]
        ),
        yaxis=dict(
            showgrid=False,
            zeroline=False,
            visible=False,
            range=[-20, 120]
        ),
        plot_bgcolor='white',
        margin=dict(l=0, r=0, t=30, b=0),
        title = dict(
            text = f"{challenge_team} {challenge_side} Challenges",
            font = dict(family = "Arial", size = 24, color = "black"),
            x = 0.5,
            y = 0.96,
            xanchor = 'center'
        ),
        legend = dict(
            y = 0.95,
            x = 0.64
        )
    )

    fig.show()

In [15]:
plot_challenge_results(pbp, 'IronPigs', 'Pitching')

## Dash App

In [34]:
import dash
from dash import dcc, html, Output, Input
import plotly.graph_objects as go

team_names = pbp['challenge_team'].unique().to_list()

# Initialize Dash app
app = dash.Dash(__name__)

app.layout = html.Div(
    children=[
        html.H1("Challenge Results Dashboard", style={'color': 'white', 'textAlign': 'center'}),

        html.Div([
            html.Label("Select Team:", style = {'color': 'white'}),
            dcc.Dropdown(
                id='team-dropdown',
                options=[{'label': team, 'value': team} for team in team_names],
                value=team_names[0],
                style={'width': '50%'}
            ),
        ], style={'margin': '10px'}),

        html.Div([
            html.Label("Select Side:", style = {'color': 'white'}),
            dcc.Dropdown(
                id='side-dropdown',
                options=[
                    {'label': 'Batting', 'value': 'Batting'},
                    {'label': 'Pitching', 'value': 'Pitching'}
                ],
                value='Batting',
                style={'width': '50%'}
            ),
        ], style={'margin': '10px'}),

        dcc.Graph(id='challenge-graph')
    ]
)

@app.callback(
    Output('challenge-graph', 'figure'),
    Input('team-dropdown', 'value'),
    Input('side-dropdown', 'value')
)
def update_graph(selected_team, selected_side):
    challenge_df = (
        pbp
            .filter(
                (pl.col('challenge_team') == selected_team) & 
                (pl.col('challenge_side') == selected_side))
            .with_columns(
                pl.when(pl.col('challenge_successful') == 'successful')
                .then(pl.lit('green'))
                .otherwise(pl.lit('red'))
                .alias('challenge_color'))
    )

    tooltip = challenge_df.select([
        'challenge_team',
        'challenge_side',
        'plate_x',
        'percentile_z',
        'original_call_challenge',
        'challenge_successful'
    ]).to_numpy()

    fig = go.Figure()

    # strike zone
    fig.add_shape(
        type="rect",
        x0=-0.83, x1=0.83,
        y0=0, y1=100,
        fillcolor="rgba(173, 216, 230, 0.3)",
        line=dict(color="black", width=2)
    )

    # scatter plot of pitches
    fig.add_trace(go.Scatter(
        x=challenge_df["plate_x"],
        y=challenge_df["percentile_z"],
        mode='markers',
        marker=dict(
            color=challenge_df['challenge_color'],
            line=dict(width=0),
            size=15
        ),
        name='Pitches',
        showlegend=False,
        customdata=tooltip,
        hovertemplate=(
            "Challenge Team: %{customdata[0]}<br>" +
            "Challenge Side: %{customdata[1]}<br>" +
            "Horizontal Location: %{customdata[2]:.2f}<br>" +
            "Vertical Location (%ile): %{customdata[3]:.1f}<br>" +
            "Initial Call: %{customdata[4]}<br>" +
            "Challenge: %{customdata[5]}<extra></extra>"
        )
    ))

    # legend for successful challenges
    fig.add_trace(go.Scatter(
        x=[None], y=[None],
        mode='markers',
        marker=dict(size=15, color='green'),
        name='Successful'
    ))

    # legend for unsuccessful challenges
    fig.add_trace(go.Scatter(
        x=[None], y=[None],
        mode='markers',
        marker=dict(size=15, color='red'),
        name='Unsuccessful'
    ))

    # formatting
    fig.update_layout(
        width=500,
        height=700,
        xaxis=dict(showgrid=False, zeroline=False, visible=False, range=[-1.1, 1.1]),
        yaxis=dict(showgrid=False, zeroline=False, visible=False, range=[-20, 120]),
        plot_bgcolor='white',
        margin=dict(l=0, r=0, t=30, b=0),
        title=dict(
            text=f"{selected_team} {selected_side} Challenges",
            font=dict(family="Arial", size=24, color="black"),
            x=0.5,
            y=0.96,
            xanchor='center'
        ),
        legend=dict(
            y=0.95,
            x=0.64,
            font=dict(color="black"),
            bgcolor='rgba(0,0,0,0)'
        )
    )
    return fig

if __name__ == '__main__':
    app.run(debug=True)

# Missed Challenge Opportunities

1) called strike (lag strikes > strikes, take), was the third strike of at-bat (otherwise wouldn't have that info), not in zone, no challenge

## Connect org id to team nickname

Still in progress 
- connect team id to mlb org with join of pbp and teams
- join that back in on parent org names and filter to league_name (triple a leagues) to get team_nickname

In [17]:
teams = pl.read_csv('../data/raw_data/2024_teams.csv')
major_league_lookup = teams.select('team_id', 'parent_org_name')
triple_a_teams = teams.filter(pl.col('league_name').is_in(['International League', 'Pacific Coast League'])).select('parent_org_name', 'team_nickname')

In [18]:
team_lookup = (
    teams
        .filter(pl.col('league_name').is_in(['International League', 'Pacific Coast League']))
        .select(
            pl.col('parent_org_name').alias('org_name'),
            pl.col('team_nickname').alias('team_name')
        )
)

In [19]:
pbp = (
    pbp.join(
        team_lookup,
        left_on = 'home_team_org_name',
        right_on = 'org_name')
        .rename({'team_name': 'home_team_name'})
        .join(
            team_lookup,
            left_on = 'away_team_org_name',
            right_on = 'org_name')
        .rename({'team_name': 'away_team_name'})
)

In [20]:
pbp.join(team_lookup, left_on = 'home_team_org_name', right_on = 'org_name').select('home_team', 'team_name')

shape: (337_763, 2)
┌───────────┬──────────────┐
│ home_team ┆ team_name    │
│ ---       ┆ ---          │
│ str       ┆ str          │
╞═══════════╪══════════════╡
│ ABQ       ┆ Isotopes     │
│ BUF       ┆ Bisons       │
│ ABQ       ┆ Isotopes     │
│ WOR       ┆ Red Sox      │
│ DUR       ┆ Bulls        │
│ …         ┆ …            │
│ MEM       ┆ Redbirds     │
│ JAX       ┆ Jumbo Shrimp │
│ LV        ┆ Aviators     │
│ ABQ       ┆ Isotopes     │
│ JAX       ┆ Jumbo Shrimp │
└───────────┴──────────────┘

In [21]:
pbp = pbp.with_columns([
    pl.when(pl.col('inning_top_bot') == 'Top')
    .then(pl.col('home')),
    
    pl.when(
        # pitch was a strike
        (pl.col('strikes') > pl.col('lag_strikes')) &
        # third strike (otherwise wouldn't be able to see challenges)
        (pl.col('strikes') == 3) &
        # no swing
        (pl.col('swing') == 'take') &
        # wasn't in the strike zone (theoretically; using the plate operator heights)
        (pl.col('in_strike_zone') == 0)
    )
    .then(1)
    .otherwise(0)
    .alias('missed_challenge_batter')
]
)

ColumnNotFoundError: home

Resolved plan until failure:

	---> FAILED HERE RESOLVING 'with_columns' <---
DF ["pitch_id", "play_start_datetime", "play_end_datetime", "pitch_type", ...]; PROJECT */119 COLUMNS