# Analysis of Minor League Challenge Systems

In this file we will analyze the data we prepared in `data_prep.ipynb`.

## Questions to Pursue

1) What types of pitches and pitch locations are challenged most frequently?

2) How often are challenges successful?

3) Which batters / teams challenge most frequently?

4) Who uses their challenges most / least effectively? Could incorporate run values here

5) Can we create a challenge 'player card' visualization as a proof of concept?

## Current Blockers

1) It turns out that sz_top and sz_bottom don't align perfectly with the top and bottom of the strike zone. It would be helpful to definitiely determine whether a challenge will be successful to analyze 'missed opportunities'.

## Next Steps

1) Begin analysis with the questions above as a guide.

2) Look into using the zone column to determine whether a pitch is in the strike zone.

# Import Libraries

In [4]:
import numpy as np
import polars as pl

# Load Data

In [2]:
pbp = pl.read_csv('../data/export_data/aaa_pbp.csv')

In [3]:
pbp.head()

shape: (5, 111)
┌──────────┬────────────┬────────────┬────────────┬───┬────────────┬───────┬───────────┬───────────┐
│ pitch_id ┆ play_start ┆ play_end_d ┆ pitch_type ┆ … ┆ lag_strike ┆ swing ┆ challenge ┆ challenge │
│ ---      ┆ _datetime  ┆ atetime    ┆ ---        ┆   ┆ s          ┆ ---   ┆ ---       ┆ _successf │
│ i64      ┆ ---        ┆ ---        ┆ str        ┆   ┆ ---        ┆ str   ┆ i64       ┆ ul        │
│          ┆ str        ┆ str        ┆            ┆   ┆ i64        ┆       ┆           ┆ ---       │
│          ┆            ┆            ┆            ┆   ┆            ┆       ┆           ┆ str       │
╞══════════╪════════════╪════════════╪════════════╪═══╪════════════╪═══════╪═══════════╪═══════════╡
│ 0        ┆ 2024-06-28 ┆ 2024-06-28 ┆ CH         ┆ … ┆ 0          ┆ take  ┆ 0         ┆ no        │
│          ┆ T01:53:58. ┆ 01:54:02.7 ┆            ┆   ┆            ┆       ┆           ┆ challenge │
│          ┆ 280        ┆ 89         ┆            ┆   ┆            ┆       ┆           ┆           │
│ 1        ┆ 2024-09-18 ┆ 2024-09-18 ┆ FF         ┆ … ┆ 0          ┆ take  ┆ 0         ┆ no        │
│          ┆ T00:19:15. ┆ 00:19:25.6 ┆            ┆   ┆            ┆       ┆           ┆ challenge │
│          ┆ 010        ┆ 47         ┆            ┆   ┆            ┆       ┆           ┆           │
│ 2        ┆ 2024-07-25 ┆ 2024-07-25 ┆ SL         ┆ … ┆ 2          ┆ take  ┆ 0         ┆ no        │
│          ┆ T03:06:15. ┆ 03:06:19.2 ┆            ┆   ┆            ┆       ┆           ┆ challenge │
│          ┆ 107        ┆ 95         ┆            ┆   ┆            ┆       ┆           ┆           │
│ 3        ┆ 2024-08-03 ┆ 2024-08-03 ┆ FF         ┆ … ┆ 2          ┆ take  ┆ 0         ┆ no        │
│          ┆ T22:40:47. ┆ 22:40:51.5 ┆            ┆   ┆            ┆       ┆           ┆ challenge │
│          ┆ 492        ┆ 01         ┆            ┆   ┆            ┆       ┆           ┆           │
│ 4        ┆ 2024-08-16 ┆ 2024-08-16 ┆ CU         ┆ … ┆ 2          ┆ take  ┆ 0         ┆ no        │
│          ┆ T23:05:44. ┆ 23:05:51.5 ┆            ┆   ┆            ┆       ┆           ┆ challenge │
│          ┆ 932        ┆ 95         ┆            ┆   ┆            ┆       ┆           ┆           │
└──────────┴────────────┴────────────┴────────────┴───┴────────────┴───────┴───────────┴───────────┘

# Classify Pitch as In or Outside of Strikezone

**Horizontal limits:** x is centered at 0 and measured in feet. Home plate is 17 inches wide, and the strike zone's horizontal limits include home plate plus the diameter of the baseball (2.94 inches) = 19.94 inches = 1.66 feet. Thus, the limits of the strike zone are +- 0.83.

**Vertical limits:** Right now we're using sz_top and sz_bot +/- the diameter of the ball, but as we'll see below it's not entirely consistent with ABS results.

In [9]:
ball_types = ['B', '*B', 'P']
pbp = (
    pbp
        .with_columns(
            pl.when(
                (np.abs(pl.col('plate_x')) < 0.83) &
                (pl.col('plate_z') >= (pl.col('sz_bot') - (2.94 / 12))) &
                (pl.col('plate_z') <= (pl.col('sz_top') + (2.94 / 12)))
            )
            .then(1)
            .otherwise(0)
            .alias('in_strike_zone')
            )
        .with_columns(
            # called a ball, but in the strike zone
            pl.when(
                (
                    (pl.col('type').is_in(ball_types)) &
                    (pl.col('in_strike_zone') == 1)
                ) |
                # called a strike, but not in the strike zone
                (
                    (pl.col('swing') == 'take') &
                    (pl.col('strikes') > pl.col('lag_strikes')) &
                    (pl.col('in_strike_zone') == 0)
                )
            )
            .then(1)
            .otherwise(0)
            .alias('missed_call')
        )
)

In [10]:
# Why are there missed calls on challenged pitches?
(
    pbp
        .filter(pl.col('challenge') == 1)
        .select(pl.col('missed_call').value_counts()).unnest('missed_call')
)

shape: (2, 2)
┌─────────────┬───────┐
│ missed_call ┆ count │
│ ---         ┆ ---   │
│ i32         ┆ u32   │
╞═════════════╪═══════╡
│ 1           ┆ 110   │
│ 0           ┆ 821   │
└─────────────┴───────┘

In [13]:
a = (
    pbp
        .filter(
            (pl.col('challenge') == 1) &
            (pl.col('missed_call') == 1)
        )
        .with_columns([
            pl.col('sz_bot') - (2.94 / 12),
            pl.col('sz_top') + (2.94 / 12)
        ])
        .select(
            'balls',
            'strikes',
            'lag_balls',
            'lag_strikes',
            'plate_x',
            'plate_z',
            'sz_top',
            'sz_bot',
            'des'
        )
)
# first one: ABS determined it was a strike despite being slightly below the zone
# maybe slightly increase the width of the zone